services:
  spring:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - mysqlvolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fhirstarter

volumes:
  mysqlvolume: